# workflow 이름
name: Java CI with Gradle

# event 정의
on:
  push:
    branches:
      - main # main에 push 될 때
  pull_request:
    branches:
      - main # main에 pr 요청될 때

# job 정의
jobs:
  build-and-push-docker:

    # 이 job을 수행하는 OS ex) windows-latest, macos-12 등 / github-hosted-runner 이용 시 가상환경 사용 가능
    runs-on: ubuntu-latest
    permissions:
      contents: read

    # job에서 수행하는 step들을 정의
    steps:
      - uses: actions/checkout@v4 # Repository로부터 CI 수행 서버로 코드를 내려받는 Action
      - name: Set up JDK 17 # step 의 이름
        uses: actions/setup-java@v4 # jdk를 다운 받고 캐싱해주는 action
        with: # Action에 전달하는 input을 정의하는 곳
          java-version: '17'
          distribution: 'temurin' # jdk를 제공하는 vender사 이름 ex) zulu, adopt, microsoft

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Grant execute permission for gradlew # gradlew 를 할 수 있게 권한 부여
        run: chmod +x gradlew

      - name: Build with Gradle Wrapper # build
        run: ./gradlew clean build --exclude-task test # test 제외한 build

      - name: Docker Login # Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Image Build # Docker image build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }} .

      - name: Docker Hub Push # DockerHub로 push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}

  # EC2로 배포
  deploy-to-ec2:

    needs: build-and-push-docker
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} # EC2 인스턴스 퍼블릭 DNS
          username: ${{ secrets.EC2_USERNAME }} # ubuntu
          key: ${{ secrets.PRIVATE_KEY }} # EC2 pem key
          # 도커 작업
          script: |
            sudo docker kill ${{ secrets.PROJECT_NAME }}
            sudo docker rm -f ${{ secrets.PROJECT_NAME }}
            sudo docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}
  
            sudo docker run -p ${{ secrets.PORT }}:${{ secrets.PORT }} \
            --name ${{ secrets.PROJECT_NAME }} \
            -d ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}