# workflow 이름
name: Java CI with Gradle

# event 정의
on:
  push:
    branches:
      - main # main에 push 될 때
  pull_request:
    branches:
      - main # main에 pr 요청될 때

# job 정의
jobs:
  build:

    # 이 job을 수행하는 OS ex) windows-latest, macos-12 등 / github-hosted-runner 이용 시 가상환경 사용 가능
    runs-on: ubuntu-latest
    permissions:
      contents: read

    # job에서 수행하는 step들을 정의
    steps:
      - uses: actions/checkout@v4 # Repository로부터 CI 수행 서버로 코드를 내려받는 Action
      - name: Set up JDK 17 # step 의 이름
        uses: actions/setup-java@v4 # jdk를 다운 받고 캐싱해주는 action
        with: # Action에 전달하는 input을 정의하는 곳
          java-version: '17'
          distribution: 'temurin' # jdk를 제공하는 vender사 이름 ex) zulu, adopt, microsoft

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Grant execute permission for gradlew # gradlew 를 할 수 있게 권한 부여
        run: chmod +x gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build
